dist: trusty
language:
  - node_js
  - python

node_js:
  - '12.18.4'

python:
  - '3.6'

services:
  - docker

addons:
  sonarcloud:
    organization: "pamanda"
    token: ${SONAR_TOKEN}

cache:
  directories:
    - node_modules
    - coverage

before_install:
  - yarn install
  - pip install requests
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

stages:
  - Build
  - Test
  - Quality gate
  - Docker
  - Deploy

jobs:
  include:
    - stage: Build
      name: Build
      script:
        - yarn build

    - stage: Test
      name: Test
      script:
        - yarn run test:unit --coverage

    - stage: Quality gate
      name: Quality gate
      script:
        - sonar-scanner

    - stage: Docker
      name: Docker
      if: (NOT type IN (pull_request)) AND branch = master
      script:
        # build docker image
        - docker build -t "$DOCKER_USERNAME"/"$SERVICE_IMAGE":"$TAG_NAME" .

        # push image to Docker Hub
        - docker push "$DOCKER_USERNAME"/"$SERVICE_IMAGE":"$TAG_NAME"

    - stage: Deploy
      name: Deploy
      if: (NOT type IN (pull_request)) AND branch = master
      script: python ./upgrade_service.py