dist: trusty
language:
  - node_js

node_js:
  - '12.18.4'

services:
  - docker

addons:
  sonarcloud:
    organization: "pamanda"
    token: ${SONAR_TOKEN}

cache:
  directories:
    - node_modules
    - coverage

before_install:
  - yarn install

stages:
  - Build
  - Test
  - Quality gate

jobs:
  include:
    - stage: Build
      name: Build
      script:
        - yarn build

    - stage: Test
      name: Test
      script:
        - yarn run test:unit --coverage

    - stage: Quality gate
      name: Quality gate
      script:
        - sonar-scanner